EXPMACS =	TMACDIR=${TMACDIR} FONTDIR=${FONTDIR} NTERMDIR=${NTERMDIR} \
		TEXHYPHENS=${TEXHYPHENS} ALTHYPHENS=${ALTHYPHENS} \
		DWBHOME=${DWBHOME} BINDIR=${BINDIR} LIBDIR=${LIBDIR} \
		"CFLAGS=${CFLAGS}" "LDFLAGS=${LDFLAGS}" POSTDIR=${POSTDIR} \
		TEMPDIR=${TEMPDIR} MAN1DIR=$(MAN1DIR) MAN5DIR=$(MAN5DIR)

SUBDIRS =	common tr2post mcolor mpictures

all clean install uninstall:
		@for i in ${SUBDIRS}; do \
			(cd $$i; make -f mkfile ${EXPMACS} $@) || exit; \
		done
